# SPDX-License-Identifier: MIT-0
---
# handlers file for proxy
- name: Start HAProxy
  ansible.builtin.systemd_service:
    name: "haproxy"
    state: "started"
    enabled: true

- name: Restart Nginx
  ansible.builtin.systemd_service:
    name: "nginx"
    state: "started"
    enabled: true

- name: Validate haproxy config
  ansible.builtin.command: "haproxy -f /etc/haproxy/haproxy.cfg -c"
  changed_when: false

- name: Validate nginx config
  ansible.builtin.command: "nginx -t -c /etc/nginx/nginx.conf"
  changed_when: false

- name: Reload Nginx
  ansible.builtin.systemd_service:
    name: "nginx"
    state: "reloaded"
