apiVersion: v1
kind: Service
metadata:
  name: mc-router
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
    # - targetPort: web
    #   name: web
    #   port: 8080
    #   nodePort: 25580
    - targetPort: proxy
      name: proxy
      port: 25565
  selector:
    run: mc-router
