apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mc-router
  name: mc-router
  namespace: minecraft
spec:
  selector:
    matchLabels:
      run: mc-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mc-router
    spec:
      tolerations:
        - key: "group"
          operator: "Equal"
          value: "arm64perf"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ubuntu-arm-oracle
      serviceAccountName: mc-router
      containers:
        - image: itzg/mc-router:latest
          name: mc-router
          args:
            [
              "--api-binding",
              ":8080",
              "--in-kube-cluster",
              "--receive-proxy-protocol",
            ]
          ports:
            - name: proxy
              containerPort: 25565
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: "100m"
            limits:
              memory: 100Mi
              cpu: "250m"
