---
apiVersion: v1
kind: Service
metadata:
  name: waves
  namespace: minecraft
  annotations:
    "mc-router.itzg.me/externalServerName": "waves.mc.anurag.sh"
spec:
  ports:
    - port: 25565
      targetPort: 25565
  selector:
    run: waves
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: waves
  name: waves
  namespace: minecraft
spec:
  selector:
    matchLabels:
      run: waves
  template:
    metadata:
      labels:
        run: waves
    spec:
      tolerations:
        - key: "group"
          operator: "Equal"
          value: "arm64perf"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ubuntu-arm-oracle
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - image: itzg/minecraft-server
          name: waves
          env:
            - name: EULA
              value: "TRUE"
            - name: MOTD
              value: "Brandon made me do this"
            - name: WHITELIST
              value: |
                botplayer22
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: waves-mc-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waves-mc-data
  namespace: minecraft
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 5Gi
