# SPDX-License-Identifier: MIT-0
---
# tasks file for k3s-control
- name: Install k3s
  block:
    - name: Get Service Status
      ansible.builtin.command: "tailscale ip -4"
      register: tailscale_ip
      tags:
        - skip_ansible_lint

    - name: Template and copy config
      ansible.builtin.template:
        src: k3s-config.yaml
        dest: /etc/rancher/k3s/config.yaml
        owner: root
        mode: "0644"

    - name: Copy and Execute the script
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | sh -s - agent
      tags:
        - skip_ansible_lint
      notify: Restart K3S
