version: "3.9"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    deploy:
      restart_policy:
        condition: any
    ports:
      - 80:80
    volumes:
      - jenkins-data:/var/jenkins_home
      - /data/aur:/var/data/aur
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    privileged: true
    hostname: jenkins
    user: root
    deploy:
      restart_policy:
        condition: any
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins

    # gitlab:
    #   image: 'gitlab/gitlab-ee:latest'
    #   restart: always
    #   hostname: 'gitlab.anurag.sh'
    #   environment:
    #     GITLAB_OMNIBUS_CONFIG: |
    #       external_url 'https://gitlab.anurag.sh'
    #       # Add any other gitlab.rb configuration here, each on its own line
    #   ports:
    #     - '9090:80'
    #     - '22:22'
    #   volumes:
    #     - '$GITLAB_HOME/config:/etc/gitlab'
    #     - '$GITLAB_HOME/logs:/var/log/gitlab'
    #     - '$GITLAB_HOME/data:/var/opt/gitlab'

  registry:
    deploy:
      restart_policy:
        condition: any
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /data/registry:/var/lib/registry
    container_name: registry

volumes:
  jenkins-data:
