version: "3.9"

services:
  nginx:
    networks:
      - main-network
    build: ./nginx
    container_name: nginx
    deploy:
      restart_policy:
        condition: any
    ports:
      - 80:80
    volumes:
      - jenkins-data:/var/jenkins_home
      - /data/aur:/var/data/aur
    depends_on:
      - jenkins

  jenkins:
    networks:
      - main-network
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    privileged: true
    hostname: jenkins
    user: root
    deploy:
      restart_policy:
        condition: any
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins

  server:
    networks:
      - main-network
    image: gitea/gitea:1.14.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    deploy:
      restart_policy:
        condition: any
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

    depends_on:
        - postgres

  postgres:
    networks:
      - main-network
    image: postgres:13
    container_name: postgres
    deploy:
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

  registry:
    networks:
      - main-network
    deploy:
      restart_policy:
        condition: any
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /data/registry:/var/lib/registry
    container_name: registry

networks:
  main-network:
    name: main-network

volumes:
  gitea-data:
  jenkins-data:
