version: "3.9"

services:
  nginx:
    networks:
      - main-network
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /data/aur:/var/data/aur
      - /data/ip:/var/data/ip
      - /data/kernel:/var/data/kernel
    depends_on:
      - jenkins
      - jellyfin

  jellyfin:
    image: linuxserver/jellyfin:10.7.7
    networks:
      - main-network
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /data/plex/jellyfin-config:/config
      - /data/plex/TV:/data/tvshows
      - /data/plex/Movies:/data/movies
    expose:
      - "8096"
    restart: always

  jenkins:
    networks:
      - main-network
    image: jenkins/jenkins:2.322-alpine
    container_name: jenkins
    privileged: true
    hostname: jenkins
    user: root
    restart: always
    expose:
      - "8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    networks:
      - main-network
    restart: always
    image: registry:2.7.1
    ports:
      - 5000:5000
    volumes:
      - /data/registry:/var/lib/registry
    container_name: registry

  buildkite-agent:
    container_name: buildkite-agent
    image: buildkite/agent
    volumes:
      - /var/lib/buildkite/builds:/var/lib/buildkite/builds
      - /usr/bin/buildkite-agent:/usr/local/bin/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - BUILDKITE_AGENT_TOKEN=${BUILDKITE_AGENT_TOKEN}
        - BUILDKITE_AGENT_NAME=alpine-docker
        - BUILDKITE_BUILD_PATH=/var/lib/buildkite/builds
networks:
  main-network:
    name: main-network

volumes:
  linx-meta:
  linx-data:
  jenkins-data:
