apiVersion: v1
kind: ConfigMap
metadata:
  name: pacoloco-config
  namespace: arch-mirror
data:
  config.yaml: |
    port: 9129
    cache_dir: /pkg-cache
    purge_files_after: 360000
    download_timeout: 3600
    repos:
      alarm:
        urls:
          - http://mirror.archlinuxarm.org
      archlinux:
        urls:
          - https://sydney.mirror.pkgbuild.com
          - https://sg.mirrors.cicku.me/archlinux
          - https://au.arch.niranjan.co
          - http://sg.arch.niranjan.co
          - https://sg.arch.niranjan.co
          - http://ftp.swin.edu.au/archlinux
          - http://mirror.sg.gs/archlinux
          - https://mirror.sg.gs/archlinux
          - http://ftp.iinet.net.au/pub/archlinux
          - http://mirror.internode.on.net/pub/archlinux
    user_agent: Pacoloco/1.2
    prefetch:
      cron: 0 0 3 * * * *
      ttl_unaccessed_in_days: 30
      ttl_unupdated_in_days: 300
