apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arch-mirror
  namespace: arch-mirror
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($scheme = https) {
        more_clear_headers "Strict-Transport-Security";
      }

      rewrite ^/(.*)$ http://arch-mirror.anurag.sh/$1 permanent;
spec:
  ingressClassName: nginx
  rules:
    - host: arch-mirror.anurag.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pacoloco
                port:
                  number: 80
  tls:
    - secretName: arch-mirror-internal-tls
      hosts:
        - arch-mirror.anurag.sh
