apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arch-mirror
  name: arch-mirror-pkg-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi
