apiVersion: v1
kind: Service
metadata:
  namespace: arch-mirror
  name: pacoloco
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9129
  selector:
    app: pacoloco
