# SPDX-License-Identifier: MIT-0
---
# tasks file for ip-forward
- name: Setup tailscale ip forwarding params
  block:
    - name: Copy sysctl file for IP forwarding
      ansible.builtin.copy:
        src: ip-forward.conf
        dest: /etc/sysctl.d/99-ip-forward.conf
        owner: root
        mode: "0644"
      notify: Reload sysctl
      become: true
      become_user: root
      become_method: sudo
