version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/anurag.sh"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/azure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/graph"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/maccas"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/module"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/openai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/oracle"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/ozb"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/perthtransport"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/places"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/redis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/replybot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/sandbox"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/tf-state"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/weather"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/wireguard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/ww3"
    schedule:
      interval: "weekly"
