FROM node:14.17-alpine3.11 as clients
WORKDIR /clients

COPY ./clients/paste ./paste
RUN cd ./paste && yarn && yarn prod

FROM nginx:1.21-alpine

COPY --from=clients /clients/paste/build /www/data/paste
COPY nginx/paste.conf /etc/nginx/sites-enabled/

COPY nginx/default.conf /etc/nginx/conf.d/
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/ssl.conf /etc/nginx/ssl.conf

COPY nginx/certs/* /etc/ssl/
