# SPDX-License-Identifier: MIT-0
---
# tasks file for fix-multipathd
- name: Fix multipathd for longhorn
  block:
    - name: Copy multipathd config
      ansible.builtin.copy:
        src: multipathd.conf
        dest: /etc/multipath.conf
        owner: root
        mode: "0644"
      notify: Restart multipathd
      become: true
      become_method: sudo
      become_user: root
