version: "3.9"
services:
    paste:
        build: ./services/paste
        expose:
            - "5000"

    frontend:
        build: ./frontend
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - paste
