- name: Disable PasswordAuthentication
  hosts: all

  tasks:
    - name: Disable PasswordAuthentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication no
      notify: restart ssh

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
