- name: Fix multipathd for longhorn
  hosts:
    - optiplex
    - control
    - oracle
  become: true

  tasks:
    - name: Copy multipathd config
      ansible.builtin.template:
        src: ../config/multipathd.conf
        dest: /etc/multipath.conf
        owner: root
        mode: "0644"

    - name: Restart multipathd
      ansible.builtin.systemd_service:
        name: "multipathd"
        state: "restarted"
