- name: Install k3s server (optiplex)
  hosts:
    - optiplex
  remote_user: janitor
  become: true

  tasks:
    - name: Get Service Status
      ansible.builtin.command: "tailscale ip -4"
      register: tailscale_ip
      tags:
        - skip_ansible_lint

    - name: Template and copy config
      ansible.builtin.template:
        src: ../config/optiplex-k3s.yaml
        dest: /etc/rancher/k3s/config.yaml
        owner: root
        mode: "0644"

    - name: Copy and Execute the script
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | sh -s - server
      tags:
        - skip_ansible_lint

    - name: Restart K3S
      ansible.builtin.systemd_service:
        name: "k3s"
        state: "restarted"
