- name: Install tailscale
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: Get Service Status
      ansible.builtin.systemd:
        name: "tailscaled"
      register: tailscale_service_status

    - name: Copy and Execute the script
      ansible.builtin.shell: curl -fsSL https://tailscale.com/install.sh | sh
      tags:
        - skip_ansible_lint
      when: tailscale_service_status.status.ActiveState != 'active'
