- name: Setup Proxy
  hosts: proxy
  become: true

  tasks:
    - name: Install Packages
      ansible.builtin.apt:
        package:
          - haproxy
          - nginx
          - libnginx-mod-stream

    - name: Get tailscale ip
      ansible.builtin.command: "tailscale ip -4"
      register: tailscale_ip
      tags:
        - skip_ansible_lint

    - name: Template and copy haproxy config
      ansible.builtin.template:
        src: ../config/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        mode: "0644"

    - name: Validate haproxy config
      ansible.builtin.command: "haproxy -f /etc/haproxy/haproxy.cfg -c"

    - name: Copy nginx config
      ansible.builtin.copy:
        src: ../config/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        mode: "0644"

    - name: Copy allowed-domains.txt
      ansible.builtin.copy:
        src: ../config/allowed-domains.txt
        dest: /etc/haproxy/allowed-domains.txt
        owner: root
        mode: "0644"

    - name: Restart HAProxy
      ansible.builtin.systemd_service:
        name: "haproxy"
        state: "restarted"

    - name: Restart Nginx
      ansible.builtin.systemd_service:
        name: "nginx"
        state: "restarted"
