- name: Setup Proxy
  hosts: proxy
  remote_user: root
  become: true

  tasks:
    - name: Install Packages
      ansible.builtin.apt:
        package:
          - haproxy
          - nginx
          - libnginx-mod-stream

    - name: Copy HAProxy config
      ansible.builtin.copy:
        src: ../config/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        mode: "0644"

    - name: Copy nginx config
      ansible.builtin.copy:
        src: ../config/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        mode: "0644"

    - name: Copy allowed-domains.txt
      ansible.builtin.copy:
        src: ../config/allowed-domains.txt
        dest: /etc/haproxy/allowed-domains.txt
        owner: root
        mode: "0644"

    - name: Restart HAProxy
      ansible.builtin.systemd_service:
        name: "haproxy"
        state: "restarted"

    - name: Restart Nginx
      ansible.builtin.systemd_service:
        name: "nginx"
        state: "restarted"
