- name: Upgrade k3s (server)
  hosts:
    - control
    - optiplex
  become: true

  tasks:
    - name: Copy and Execute the script
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | sh -s - server
      tags:
        - skip_ansible_lint
