version: "3.9"

services:
  nginx:
    networks:
      - main-network
    build:
      context: ../../
      dockerfile: ./services/files/Dockerfile
    volumes:
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - linx-server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - /var/lib/letsencrypt:/var/lib/letsencrypt:rw
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
    depends_on:
      - nginx
    command: certonly --webroot --force-renewal --webroot-path=/usr/share/nginx/html --email contact@anurag.sh --agree-tos --no-eff-email -d files.anurag.sh

  linx-server:
    container_name: linx-server
    image: andreimarcu/linx-server:version-2.3.8
    command: -config /data/linx-server.conf
    volumes:
      - linx-data:/data/files
      - linx-meta:/data/meta
      - ./linx/linx-server.conf:/data/linx-server.conf:ro
    networks:
      - main-network
    expose:
      - "8080"
    restart: always

networks:
  main-network:
    name: main-network

volumes:
  linx-meta:
  linx-data:
