# SPDX-License-Identifier: MIT-0
---
# handlers file for uptime-kuma
- name: Run uptime-kuma
  ansible.builtin.command:
    cmd: docker compose up --build -d --pull=always
    chdir: /root/deployment
  become: true
  become_method: sudo
  become_user: root
  changed_when: true
