apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.8.8
      helm:
        valuesObject:
          global:
            domain: argocd.inf-k8s.net

          configs:
            cm:
              admin.enabled: false
            rbac:
              policy.csv: |
                p, anurag, *, *, *, allow
                p, github-actions, applications, sync, default/*, allow
                p, github-actions, applications, get, default/*, allow
                p, github-actions, projects, get, *, allow
            params:
              server.insecure: true

          server:
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              extraTls:
                - hosts:
                    - argocd.inf-k8s.net
                  secretName: argocd-inf-k8s-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
