apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.7.23
      helm:
        valuesObject:
          global:
            domain: argocd.internal.anurag.sh

          configs:
            params:
              server.insecure: true

          server:
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              extraTls:
                - hosts:
                    - argocd.internal.anurag.sh
                  secretName: argocd-wildcard-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
