apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.16.2
      helm:
        values: |
          crds:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
