apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.17.0
      helm:
        values: |
          crds:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
