apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-cluster
  namespace: argocd
spec:
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/bootstrap/initdb/postInitApplicationSQL
        - /spec/managed
        - /spec/postgresql/shared_preload_libraries
        - /spec/priorityClassName
        - /spec/storage/storageClass
        - /spec/postgresql/pg_hba
        - /spec/postgresql/pg_ident
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: cluster
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.2.1
      helm:
        valuesObject:
          backups:
            enabled: true
            endpointURL: "https://45c8799279b4d50c2126b6188d93045c.r2.cloudflarestorage.com"
            s3:
              bucket: "pg-cluster-backup"
            secret:
              create: false
            wal:
              encryption: null
            data:
              encryption: null
            retentionPolicy: "7d"
          cluster:
            monitoring:
              enabled: true
              podMonitor:
                enabled: true
              prometheusRule:
                enabled: false
            affinity:
              podAntiAffinityType: preferred
              topologyKey: kubernetes.io/hostname
              enablePodAntiAffinity: true
              # nodeAffinity:
              #   requiredDuringSchedulingIgnoredDuringExecution:
              #     nodeSelectorTerms:
              #       - matchExpressions:
              #           - key: kubernetes.io/hostname
              #             operator: In
              #             values:
              #               - k8s-optiplex-1
              #               - k8s-optiplex-2
              #               - k8s-optiplex-3
            storage:
              size: "30Gi"
            postgresql:
              parameters:
                pg_stat_statements.max: "10000"
                pg_stat_statements.track: all
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
