apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
  project: default
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.23.0

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
