apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flexo
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - repoURL: https://github.com/Accurate0/infrastructure.git
      path: cluster/kubernetes/flexo

  destination:
    server: https://kubernetes.default.svc
    namespace: flexo

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
