apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: v4.11.3

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
