apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: v4.11.3
      helm:
        valuesObject:
          controller:
            tolerations:
              - key: "group"
                operator: "Equal"
                value: "external"
                effect: "NoSchedule"
            config:
              proxy-hide-headers: "Server, X-Powered-By"
              server-tokens: "False"
              enable-modsecurity: "True"
              enable-owasp-modsecurity-crs: "True"
              enable-real-ip: "True"
              allow-snippet-annotations: "True"
              modsecurity-snippet: |
                SecRuleEngine DetectionOnly
                SecRequestBodyAccess On
                SecAuditLog /var/log/modsec_audit.log
            kind: DaemonSet

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
