apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 66.1.1
      helm:
        valuesObject:
          prometheus:
            ingress:
              enabled: false
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - prometheus.internal.anurag.sh
              tls:
                - secretName: prometheus-server-tls
                  hosts:
                    - prometheus.internal.anurag.sh
            prometheusSpec:
              externalUrl: "https://prometheus.internal.anurag.sh"
              retention: 1d
              retentionSize: "5GB"
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn-prod
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 5Gi
          kubeEtcd:
            enabled: true
            endpoints:
              - 100.70.180.118
              - 100.89.112.112
              - 100.115.217.79
              - 100.66.108.81
            service:
              enabled: true
              port: 2381
              targetPort: 2381
          alertmanager:
            enabled: false
          grafana:
            # Provision grafana-dashboards-kubernetes
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                  - name: "grafana-dashboards-kubernetes"
                    orgId: 1
                    folder: "Kubernetes"
                    type: file
                    disableDeletion: true
                    editable: true
                    options:
                      path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
            dashboards:
              grafana-dashboards-kubernetes:
                k8s-system-api-server:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
                  token: ""
                k8s-system-coredns:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
                  token: ""
                k8s-views-global:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
                  token: ""
                k8s-views-namespaces:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
                  token: ""
                k8s-views-nodes:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
                  token: ""
                k8s-views-pods:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
                  token: ""
            persistence:
              enabled: true
              storageClassName: longhorn-prod
              size: 1Gi
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - grafana.internal.anurag.sh
              tls:
                - secretName: grafana-server-tls
                  hosts:
                    - grafana.internal.anurag.sh

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
