apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: kured
      repoURL: https://kubereboot.github.io/charts
      targetRevision: 5.6.0
      helm:
        valuesObject:

  destination:
    server: https://kubernetes.default.svc
    namespace: kured

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
