apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.2
      helm:
        valuesObject:
          global:
            tolerations:
              - effect: NoSchedule
                key: group
                operator: Equal
                value: external
              - effect: NoSchedule
                key: group
                operator: Equal
                value: arm64perf
          longhornUI:
            replicas: 1
          preUpgradeChecker:
            jobEnabled: false
          ingress:
            enabled: true
            secureBackends: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/enable-modsecurity: "False"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            host: longhorn.internal.anurag.sh
            tls: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
