apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: minio
      repoURL: https://charts.min.io
      targetRevision: 5.4.0
      helm:
        valuesObject:
          replicas: 3
          persistence:
            size: 50Gi
          environment:
            MINIO_DOMAIN: s3.inf-k8s.net
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - minio.inf-k8s.net
            tls:
              - secretName: minio-inf-k8s
                hosts:
                  - minio.inf-k8s.net
          consoleIngress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            path: /
            hosts:
              - console.minio.inf-k8s.net
            tls:
              - secretName: console-minio-inf-k8s
                hosts:
                  - console.minio.inf-k8s.net
          users:
            - accessKey: anurag
              secretKey: thispasswordhasbeenchangedlol
              policy: consoleAdmin
          resources:
            requests:
              memory: 200Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
