apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin4
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: pgadmin4
      repoURL: https://helm.runix.net
      targetRevision: 1.33.3
      helm:
        valuesObject:
          persistentVolume:
            enabled: true
            storageClassName: longhorn-prod
            size: 1Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: pgadmin.internal.anurag.sh
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: pgadmin-server-tls
                hosts:
                  - pgadmin.internal.anurag.sh

  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin4

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
