apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  ignoreDifferences:
    - group: "*"
      kind: Secret
      name: redis
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: redis
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 20.4.0
      helm:
        valuesObject:
          replica:
            persistence:
              size: 5Gi
            replicaCount: 2
            initContainers:
              - name: repair-redis
                image: docker.io/bitnami/redis:7.4.1-debian-12-r2
                command:
                  [
                    "sh",
                    "-c",
                    "yes | redis-check-aof --fix /data/appendonlydir/*.aof",
                  ]
                volumeMounts:
                  - mountPath: /data
                    name: redis-data
          master:
            persistence:
              size: 5Gi
            initContainers:
              - name: repair-redis
                image: docker.io/bitnami/redis:7.4.1-debian-12-r2
                command:
                  [
                    "sh",
                    "-c",
                    "yes | redis-check-aof --fix /data/appendonlydir/*.aof",
                  ]
                volumeMounts:
                  - mountPath: /data
                    name: redis-data
          auth:
            existingSecret: redis
            existingSecretPasswordKey: redis-password

  destination:
    server: https://kubernetes.default.svc
    namespace: redis-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
