apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: mend-renovate-ce
      repoURL: https://mend.github.io/renovate-ce-ee
      targetRevision: v9.1.1
      helm:
        valuesObject:
          postgresql:
            enabled: true
            host: cloudnative-pg-cluster-rw.cnpg-system
            port: 5432
            database: renovate
            user: renovate
          ingress:
            enabled: false
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - renovate.internal.anurag.sh
            tls:
              - secretName: renovate-internal-tls
                hosts:
                  - renovate.internal.anurag.sh
          cachePersistence:
            enabled: true
            storageClass: "longhorn-prod"
            accessModes:
              - ReadWriteOnce
            size: 1Gi
          renovate:
            mendRnvAcceptTos: y
            mendRnvPlatform: "github"
            existingSecret: renovate-config-managed-secret
            logLevel: debug
            mendRnvAdminApiEnabled: true
            config: |
              module.exports = {
                repositories: ["Accurate0/infrastructure"],
                lockFileMaintenance: { "enabled": true },
              }

          # existingSecret: "renovate-config-managed-secret"
          # cronjob:
          #   schedule: "0 */1 * * *"
          #   timeZone: "Australia/Perth"
          # persistence:
          #   cache:
          #     enabled: true
          #     storageClass: "longhorn-prod"
          #     storageSize: "1Gi"
          # renovate:
          #   config: |
          #     {
          #       "platform": "github",
          #       "repositories": ["Accurate0/infrastructure"],
          #       "lockFileMaintenance": { "enabled": true },
          #       "username": "renovate[bot]",
          #       "gitAuthor": "renovate[bot]<renovate@anurag.sh>"
          #     }

  destination:
    server: https://kubernetes.default.svc
    namespace: renovate

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
