apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: mend-renovate-ce
      repoURL: https://mend.github.io/renovate-ce-ee
      targetRevision: v9.1.1
      helm:
        valuesObject:
          postgresql:
            enabled: true
            host: cloudnative-pg-cluster-rw.cnpg-system
            port: 5432
            database: renovate
            user: renovate
          ingress:
            enabled: false
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - renovate.internal.anurag.sh
            tls:
              - secretName: renovate-internal-tls
                hosts:
                  - renovate.internal.anurag.sh
          cacheInMemory:
            enabled: true
          renovate:
            mendRnvAcceptTos: y
            mendRnvPlatform: "github"
            mendRnvCronJobSchedulerAll: "0 */1 * * *"
            existingSecret: renovate-config-managed-secret
            logLevel: debug
            mendRnvAdminApiEnabled: true
            mendRnvEnqueueJobsOnStartup: "enabled"
            extraEnvVars:
              - name: DOCKER_DOCKER_IO_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: renovate-config-managed-secret
                    key: DOCKER_DOCKER_IO_PASSWORD
                    optional: true
              - name: DOCKER_DOCKER_IO_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: renovate-config-managed-secret
                    key: DOCKER_DOCKER_IO_USERNAME
                    optional: true
            mendRnvAutoDiscoverFilter: "Accurate0/spotify-sync,Accurate0/infrastructure,Accurate0/maccas-api,Accurate0/ozb,Accurate0/replybot,Accurate0/tldr-bot"
            config: |
              module.exports = {
                extends: ["group:allNonMajor"],
                lockFileMaintenance: { "enabled": true },
                hostRules: [
                  {
                    "hostType": "docker",
                    "matchHost": "docker.io",
                    "username": process.env.DOCKER_DOCKER_IO_USERNAME,
                    "password": process.env.DOCKER_DOCKER_IO_PASSWORD,
                  },
                  {
                    "hostType": "docker",
                    "matchHost": "docker.com",
                    "username": process.env.DOCKER_DOCKER_IO_USERNAME,
                    "password": process.env.DOCKER_DOCKER_IO_PASSWORD,
                  },
                ],
                packageRules: [
                  {
                    "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
                    "automerge": true
                  }
                ],
              }

  destination:
    server: https://kubernetes.default.svc
    namespace: renovate

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
