apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: mend-renovate-ce
      repoURL: https://mend.github.io/renovate-ce-ee
      targetRevision: 9.5.0
      helm:
        valuesObject:
          postgresql:
            enabled: true
            host: cloudnative-pg-cluster-rw.cnpg-system
            port: 5432
            database: renovate
            user: renovate
          ingress:
            enabled: false
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - renovate.internal.anurag.sh
            tls:
              - secretName: renovate-internal-tls
                hosts:
                  - renovate.internal.anurag.sh
          cachePersistence:
            enabled: true
            storageClass: "longhorn-single"
            accessModes:
              - ReadWriteOnce
            size: 10Gi
          cacheInMemory:
            enabled: false
          podSecurityContext:
            runAsUser: 1000
            fsGroup: 1000
          renovate:
            mendRnvAcceptTos: y
            mendRnvPlatform: "github"
            mendRnvCronJobSchedulerAll: "*/15 * * * *"
            existingSecret: renovate-config-managed-secret
            logLevel: info
            mendRnvAdminApiEnabled: true
            mendRnvEnqueueJobsOnStartup: "enabled"
            extraEnvVars:
              - name: RENOVATE_X_DOCKER_HUB_DISABLE_LABEL_LOOKUP
                value: "true"
              - name: DOCKER_DOCKER_IO_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: renovate-config-managed-secret
                    key: DOCKER_DOCKER_IO_PASSWORD
                    optional: true
              - name: DOCKER_DOCKER_IO_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: renovate-config-managed-secret
                    key: DOCKER_DOCKER_IO_USERNAME
                    optional: true
            mendRnvAutoDiscoverFilter: "Accurate0/spotify-sync,Accurate0/infrastructure,Accurate0/maccas-api,Accurate0/ozb,Accurate0/replybot,Accurate0/tldr-bot,Accurate0/perth-transport-map,Accurate0/ingress-home,Accurate0/anurag.sh,Accurate0/pg-db-controller"
            config: |
              module.exports = {
                reviewers: ["Accurate0"],
                extends: ["group:allNonMajor"],
                timezone: "Australia/Perth",
                lockFileMaintenance: { "enabled": false, "automerge": true },
                schedule: ["* 0-3 * * 0,6"],
                packageRules: [
                  {
                    "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
                    "matchCurrentVersion": "!/^0/",
                    "automergeType": "branch",
                    "automerge": true
                  },
                  { "matchCategories": ["docker"], "enabled": false },
                ],
              }

  destination:
    server: https://kubernetes.default.svc
    namespace: renovate

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
