- name: Setup K3S agents
  hosts: agent
  become: true
  become_user: janitor

  roles:
    - role: user-management
      become: true
      become_method: sudo
      become_user: root

    - role: required-packages
    - role: ssh-config
    - role: fix-multipathd
    - role: tailscale
      vars:
        tailscale_join_network: false
    - role: ip-forward
    - role: k3s-agent
      vars:
        k3s_control_ip: https://100.66.108.81:6443
        tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
        k3s_cluster_token: "{{ lookup('ansible.builtin.env', 'K3S_CLUSTER_TOKEN') }}"
