- name: Setup K3S control
  hosts: control
  become: true
  become_user: janitor

  roles:
    - role: user-management
      become: true
      become_method: sudo
      become_user: root

    - role: required-packages
    - role: ssh-config
    - role: fix-multipathd
    - role: tailscale
      vars:
        tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
      ignore_errors: true
      # this only needs to run on the first time, k3s will reconfigure tailscale
      when: 0 > 1
    - role: k3s-control
      vars:
        tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
        k3s_cluster_token: "{{ lookup('ansible.builtin.env', 'K3S_CLUSTER_TOKEN') }}"
