- name: Setup K3S control
  hosts: control
  become: true
  serial: 1
  become_user: janitor

  roles:
    - role: user-management
      become: true
      become_method: sudo
      become_user: root

    - role: required-packages
    - role: ssh-config
    - role: fix-multipathd
    - role: tailscale
      vars:
        tailscale_join_network: false
    - role: ip-forward
    - role: k3s-control
      vars:
        tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
        k3s_cluster_token: "{{ lookup('ansible.builtin.env', 'K3S_CLUSTER_TOKEN') }}"
