apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: renovate-config-secret
  namespace: renovate
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: renovate-7t-sm
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: renovate-config-managed-secret
    secretNamespace: renovate
    creationPolicy: "Owner"
