vpn-auth: "name=tailscale,joinKey={{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }},extraArgs=--advertise-exit-node"
disable:
  - traefik
node-external-ip: "{{ tailscale_ip.stdout }}"
node-ip: "{{ tailscale_ip.stdout }}"
server: https://100.66.108.81:6443
etcd-expose-metrics: true
token: "{{ lookup('ansible.builtin.env', 'K3S_CLUSTER_TOKEN') }}"
