apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: pod-scheduler-name
  namespace: gatekeeper-system
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]

  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]

    # Adjust this to a label that is present on the pods of your custom scheduler.
    # It's important that you leave your custom scheduler to be itself scheduled by the
    # default scheduler, as otherwise if all pods of your custom scheduler somehow get
    # terminated, they won't be able to start up again due to not being scheduled.
    labelSelector:
      matchExpressions:
        - key: component
          operator: NotIn
          values: ["scheduler"]

  location: "spec.schedulerName"

  # Adjust this to match the desired profile name from your scheduler's configuration.
  parameters:
    assign:
      value: scheduler-plugins-scheduler
