# SPDX-License-Identifier: MIT-0
---
# handlers file for docker
- name: Enable docker
  ansible.builtin.service:
    name: docker
    state: "started"
    enabled: true
  become: true
  become_method: sudo
  become_user: root
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: "restarted"
  become: true
  become_method: sudo
  become_user: root
