# SPDX-License-Identifier: MIT-0
---
# tasks file for required-packages
- name: Install required packages
  block:
    - name: Install Packages
      ansible.builtin.apt:
        package:
          - nfs-common
          - neovim
          - htop
