# SPDX-License-Identifier: MIT-0
---
# tasks file for proxy
- name: Setup Proxy
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: Install Packages
      ansible.builtin.apt:
        package:
          - haproxy
          - nginx
          - libnginx-mod-stream
      notify:
        - Start Nginx
        - Start Haproxy

    - name: Get tailscale ip
      ansible.builtin.command: "tailscale ip -4"
      register: tailscale_ip
      tags:
        - skip_ansible_lint

    - name: Copy allowed-domains.txt
      ansible.builtin.copy:
        src: allowed-domains.txt
        dest: /etc/haproxy/allowed-domains.txt
        owner: root
        mode: "0644"
      notify:
        - Reload Haproxy

    - name: Template and copy haproxy config
      ansible.builtin.template:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        mode: "0644"
        validate: "haproxy -f %s -c"
      notify:
        - Reload Haproxy

    - name: Copy nginx config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        mode: "0644"
        validate: "nginx -t -c %s"
      notify:
        - Reload Nginx
