services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - MYSQL_DATABASE=uptime
      - MYSQL_USER=user
      - MYSQL_PASSWORD=supersecure
    volumes:
      - ./mariadb:/config
    networks:
      - caddy
    ports:
      - 3306:3306
    restart: unless-stopped

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:beta
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: "uptime.inf-k8s.net, uptime.anurag.sh"
      caddy.reverse_proxy: "{{upstreams 3001}}"

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
