apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waves-volume
  namespace: minecraft-waves
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-prod
  resources:
    requests:
      storage: 10Gi
