vpn-auth: "name=tailscale,joinKey={{ k3s_tailscale_auth_key }},extraArgs=--advertise-exit-node"
disable:
  - traefik
node-external-ip: "{{ tailscale_ip.stdout }}"
node-ip: "{{ tailscale_ip.stdout }}"
server: https://100.66.108.81:6443
tls-san:
  - "100.97.97.24"
  - "internal.anurag.sh"
  - "inf-k8s.net"
etcd-expose-metrics: true
token: "{{ k3s_cluster_token }}"
