apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: flexo
  name: flexo-pkg-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 50Gi
