# SPDX-License-Identifier: MIT-0
---
# tasks file for ssh-config
- name: Disable PasswordAuthentication
  block:
    - name: Disable PasswordAuthentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication no
      notify: Restart SSH
