apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-app
  namespace: dawarich
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: dawarich-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dawarich-app
    spec:
      containers:
        - args:
            - bin/rails
            - server
            - -p
            - "3000"
            - -b
            - "::"
          command:
            - web-entrypoint.sh
          envFrom:
            - secretRef:
                name: dawarich-managed-secrets
          env:
            - name: APPLICATION_HOSTS
              value: dawarich.internal.anurag.sh
            - name: APPLICATION_PROTOCOL
              value: http
            - name: DISTANCE_UNIT
              value: km
            - name: MIN_MINUTES_SPENT_IN_CITY
              value: "60"
            - name: PROMETHEUS_EXPORTER_ENABLED
              value: "false"
            - name: PROMETHEUS_EXPORTER_HOST
              value: 0.0.0.0
            - name: PROMETHEUS_EXPORTER_PORT
              value: "9394"
            - name: RAILS_ENV
              value: production
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: TIME_ZONE
              value: Australia/Perth
          image: freikin/dawarich:latest
          livenessProbe:
            exec:
              command:
                - wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '"status"\s*:\s*"ok"'
            failureThreshold: 30
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: dawarich-app
          ports:
            - containerPort: 3000
              protocol: TCP
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /var/app/public
              name: dawarich-public
            - mountPath: /var/app/tmp/imports/watched
              name: dawarich-watched
      volumes:
        - name: dawarich-public
          persistentVolumeClaim:
            claimName: dawarich-public
        - name: dawarich-watched
          persistentVolumeClaim:
            claimName: dawarich-watched
