apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dawarich-app
  namespace: dawarich
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  rules:
    - host: dawarich.inf-k8s.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dawarich-app
                port:
                  number: 3000
    - host: dawarich.anurag.sh
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: dawarich-app
                port:
                  number: 3000
  tls:
    - secretName: dawarich-inf-k8s-tls
      hosts:
        - dawarich.inf-k8s.net
    - secretName: dawarich-tls
      hosts:
        - dawarich.anurag.sh
