apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dawarich
  name: photon-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 200Gi
