apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: dawarich-public
  name: dawarich-public
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
