apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: dawarich-secrets
  namespace: dawarich
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: dawarich-pvbb
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: dawarich-managed-secrets
    secretNamespace: dawarich
    creationPolicy: "Owner"
