apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: dawarich-watched
  name: dawarich-watched
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
