apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: owntracks-recorder-store
  name: owntracks-recorder-store
spec:
  storageClassName: longhorn-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
