- name: Allow all in tailscale0
  community.general.ufw:
    rule: "{{ 'allow' if firewall_allow_tailscale == true else 'deny' }}"
    interface: tailscale0
    direction: in

- name: Allow all out tailscale0
  community.general.ufw:
    rule: "{{ 'allow' if firewall_allow_tailscale == true else 'deny' }}"
    interface: tailscale0
    direction: out
