name: call-terraform
on:
  workflow_dispatch:
    inputs:
      directory:
        type: string
        required: true
  workflow_call:
    inputs:
      directory:
        type: string
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.directory }}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
          terraform_version: latest

      - name: terraform fmt
        run: terraform fmt -recursive

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -auto-approve
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
          TF_VAR_ARM_B2C_CLIENT_ID: ${{ secrets.ARM_B2C_CLIENT_ID }}
          TF_VAR_ARM_B2C_CLIENT_SECRET: ${{ secrets.ARM_B2C_CLIENT_SECRET }}
          TF_VAR_ARM_B2C_TENANT_ID: ${{ secrets.ARM_B2C_TENANT_ID }}
          MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TF_VAR_UPSTASH_API_KEY: ${{ secrets.TF_VAR_UPSTASH_API_KEY }}
          TF_VAR_UPSTASH_EMAIL: ${{ secrets.TF_VAR_UPSTASH_EMAIL }}
