name: cloudflare
on:
  push:
    branches: [ main ]
    paths:
      - terraform/cloudflare/**
      - .github/workflows/cloudflare.yml

jobs:
  provision:
    uses: ./.github/workflows/terraform.yml
    with:
      name: cloudflare
