name: infrastructure
on:
  push:
    branches: [ main ]
    paths:
      - cloud/**
      - services/**
      - .github/workflows/infrastructure.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./cloud/terraform"

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_hostname: app.terraform.io
        cli_config_credentials_token: ${{ secrets.tf_token }}
        terraform_version: 1.1.2

    - name: terraform fmt
      run: terraform fmt -recursive

    - name: terraform init
      run: terraform init

    - name: terraform validate
      run: terraform validate

    - name: terraform plan
      run: terraform plan

    - name: terraform apply
      run: terraform apply -auto-approve

  dns:
    needs: terraform
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
    defaults:
      run:
        working-directory: "./cloud/terraform"

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_hostname: app.terraform.io
        cli_config_credentials_token: ${{ secrets.tf_token }}
        terraform_version: 1.1.2
        terraform_wrapper: false
    - run: terraform init

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g cloudflare-cli

    - name: update dns
      run: ../dns.sh

  setup-oracle:
    needs: dns
    runs-on: ubuntu-latest
    env:
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
    defaults:
      run:
        working-directory: "./cloud"
    steps:
      - uses: actions/checkout@v2
      - run: "./setup_ubuntu.sh"

  setup-linode:
    needs: dns
    runs-on: ubuntu-latest
    env:
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
    defaults:
      run:
        working-directory: "./cloud"
    steps:
        - uses: actions/checkout@v2
        - run: "./setup_arch.sh"


  check-file-changes:
    needs:
      - setup-oracle
      - setup-linode
    runs-on: ubuntu-latest

    outputs:
      paste-changed: ${{ steps.paste-changed.outputs.changed }}
      files-changed: ${{ steps.files-changed.outputs.changed }}
      jenkins-changed: ${{ steps.jenkins-changed.outputs.changed }}
      buildmachine-changed: ${{ steps.buildmachine-changed.outputs.changed }}
      zigbee-changed: ${{ steps.zigbee-changed.outputs.changed }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get paste changed files
        id: changed-files-paste
        uses: tj-actions/changed-files@v12.2
        with:
          files: |
            services/paste
            cloud/deploy_paste.sh
            cloud/terraform
            .github/

      - name: Run step if any of paste files changed
        id: paste-changed
        if: steps.changed-files-paste.outputs.any_changed == 'true' || steps.changed-files-paste.outputs.any_deleted == 'true'
        run: echo "::set-output name=changed::true"

      - name: Get files changed files
        id: changed-files-files
        uses: tj-actions/changed-files@v12.2
        with:
          files: |
            services/files
            cloud/deploy_files.sh
            cloud/terraform
            .github/

      - name: Run step if any of files files changed
        id: files-changed
        if: steps.changed-files-files.outputs.any_changed == 'true' || steps.changed-files-files.outputs.any_deleted == 'true'
        run: echo "::set-output name=changed::true"

      - name: Get jenkins changed files
        id: changed-files-jenkins
        uses: tj-actions/changed-files@v12.2
        with:
          files: |
            services/jenkins
            cloud/deploy_jenkins.sh
            cloud/deploy_buildmachine.sh
            cloud/deploy_buildmachine_2.sh
            cloud/terraform
            .github/

      - name: Run step if any of jenkins files changed
        id: jenkins-changed
        if: steps.changed-files-jenkins.outputs.any_changed == 'true' || steps.changed-files-jenkins.outputs.any_deleted == 'true'
        run: echo "::set-output name=changed::true"

      - name: Get zigbee changed files
        id: changed-files-zigbee
        uses: tj-actions/changed-files@v12.2
        with:
          files: |
            services/zigbee2mqtt
            cloud/deploy_zigbee2mqtt.sh
            .github/

      - name: Run step if any of zigbee files changed
        id: zigbee-changed
        if: steps.changed-files-zigbee.outputs.any_changed == 'true' || steps.changed-files-zigbee.outputs.any_deleted == 'true'
        run: echo "::set-output name=changed::true"

  deploy-files:
    if: needs.check-file-changes.outputs.files-changed == 'true'
    needs: check-file-changes
    runs-on: ubuntu-latest

    env:
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
    defaults:
      run:
        working-directory: "./cloud"

    steps:
      - uses: actions/checkout@v2
      - run: "./deploy_files.sh"

  deploy-paste:
    if: needs.check-file-changes.outputs.paste-changed == 'true'
    needs: check-file-changes
    runs-on: ubuntu-latest

    env:
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
    defaults:
      run:
        working-directory: "./cloud"

    steps:
      - uses: actions/checkout@v2
      - run: "./deploy_paste.sh"

  deploy-jenkins:
    if: needs.check-file-changes.outputs.jenkins-changed == 'true'
    needs: check-file-changes
    runs-on: ubuntu-latest

    env:
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
    defaults:
      run:
        working-directory: "./cloud"

    steps:
      - uses: actions/checkout@v2
      - run: "./deploy_jenkins.sh"

  deploy-buildmachine:
    if: needs.check-file-changes.outputs.jenkins-changed == 'true'
    needs:
      - check-file-changes
      - deploy-jenkins
    runs-on: ubuntu-latest

    env:
      JENKINS_EXEC_SECRET: ${{ secrets.JENKINS_EXEC_SECRET }}
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
    defaults:
      run:
        working-directory: "./cloud"

    steps:
      - uses: actions/checkout@v2
      - run: "./deploy_buildmachine.sh"

  deploy-zigbee2mqtt:
    if: needs.check-file-changes.outputs.zigbee-changed == 'true'
    needs:
      - check-file-changes
    runs-on: ubuntu-latest

    env:
      INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
    defaults:
      run:
        working-directory: "./cloud"

    steps:
      - uses: actions/checkout@v2
      - run: "./deploy_zigbee2mqtt.sh"
