name: oracle
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - oracle/**
      - .github/workflows/oracle.yml
      - .github/workflows/tf.yml
      - servers/oracle1/**
      - servers/oracle2/**

env:
  USERNAME: ubuntu
  ORACLE1_HOST: oracle1.anurag.sh
  ORACLE2_HOST: oracle2.anurag.sh

jobs:
  provision:
    uses: ./.github/workflows/old-tf.yml
    with:
      directory: oracle
    secrets:
      tf_token: ${{ secrets.tf_token }}

  update-install:
    runs-on: ubuntu-latest
    needs: provision
    defaults:
      run:
        working-directory: "./cloud"
    steps:
      - name: install/update dependencies
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.ORACLE1_HOST }},${{ env.ORACLE2_HOST }}
          sync: true
          username: ${{ env.USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y \
                ca-certificates \
                curl \
                gnupg \
                lsb-release

            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --no-tty --dearmor --batch -o /usr/share/keyrings/docker-archive-keyring.gpg

            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io rsync python3-pip zstd

            sudo systemctl daemon-reload
            sudo systemctl enable --now --no-block docker.service
            sudo usermod -a -G docker ubuntu
            sudo pip install docker-compose

  deploy-oracle1:
    needs: update-install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: deploy
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -avz --delete --progress
          remote_path: /home/${{ env.USERNAME }}/
          remote_host: ${{ env.ORACLE1_HOST }}
          remote_user: ${{ env.USERNAME }}
          remote_key: ${{ secrets.INSTANCE_KEY }}
          path: servers/oracle1

      - name: activate deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.ORACLE1_HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          script: |
            cd oracle1
            docker-compose up --build -d --remove-orphans
            docker ps

  deploy-oracle2:
    if: ${{ false }}
    needs: update-install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: deploy
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -avz --delete --progress
          remote_path: /home/${{ env.USERNAME }}/servers
          remote_host: ${{ env.ORACLE2_HOST }}
          remote_user: ${{ env.USERNAME }}
          remote_key: ${{ secrets.INSTANCE_KEY }}
          path: servers/oracle2

      - name: activate deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.ORACLE2_HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          script: |
            cd servers/oracle2

            pushd certbot
            sudo cp certbot-renewal.* /etc/systemd/system/
            sudo sh -c 'systemctl daemon-reload && systemctl enable --now certbot-renewal.timer'
            popd

            docker network prune -f
            docker-compose up --build -d
            docker ps
