name: oracle
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - oracle/**
      - .github/workflows/oracle.yml
      - .github/workflows/call-terraform-remote.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  USERNAME: ubuntu
  ORACLE_HOST: oracle.anurag.sh

jobs:
  provision:
    uses: ./.github/workflows/call-terraform-remote.yml
    with:
      directory: oracle
    secrets:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}

  update-install:
    runs-on: ubuntu-latest
    needs: provision
    defaults:
      run:
        working-directory: "./cloud"
    steps:
      - name: install/update dependencies
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.ORACLE_HOST }}
          sync: true
          username: ${{ env.USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y \
                ca-certificates \
                curl \
                gnupg \
                lsb-release

            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --no-tty --dearmor --batch -o /usr/share/keyrings/docker-archive-keyring.gpg

            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io rsync python3-pip zstd

            sudo systemctl daemon-reload
            sudo systemctl enable --now --no-block docker.service
            sudo usermod -a -G docker ubuntu
            sudo pip install docker-compose
