name: provision
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ww3-api/**
      - anurag-sh/**
      - weather-api/**
      - cloudflare/**
      - light-api/**
      - azure/**
      - aws/**
      - tfc/**
      - maccas-api/**
      - places-api/**
      - kvp-api/**
      - log-api/**
      - sandbox/**
      - module/**
      - .github/workflows/call-terraform.yml
      - .github/workflows/provision.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tfc:
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: tfc
    secrets:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

  azure:
    needs: tfc
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: azure
    secrets:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  aws:
    needs: tfc
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: aws
    secrets:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  projects:
    strategy:
      fail-fast: false
      matrix:
        directory:
          - anurag-sh
          - ww3-api
          - weather-api
          - dota2-api
          - light-api
          - cloudflare
          - sandbox
          - maccas-api
          - places-api
          - kvp-api
          - log-api

    name: ${{ matrix.directory }}
    runs-on: ubuntu-latest
    needs:
      - azure
      - aws
    defaults:
      run:
        working-directory: "${{ matrix.directory }}"

    env:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.tf_token }}
          terraform_version: 1.3.1

      - name: terraform fmt
        run: terraform fmt -recursive

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -auto-approve
