name: provision
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ww3-api/**
      - weather-api/**
      - cloudflare/**
      - light-api/**
      - apim/**
      - tfc/**
      - .github/workflows/azure-apim-terraform.yml
      - .github/workflows/provision.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tfc:
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: tfc
    secrets:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

  apim:
    needs: tfc
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: apim
    secrets:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  terraform:
    name: ${{ matrix.directory }}
    runs-on: ubuntu-latest
    needs: apim
    defaults:
      run:
        working-directory: "${{ matrix.directory }}"
    strategy:
      fail-fast: false
      matrix:
        directory:
          - ww3-api
          - weather-api
          - light-api
          - cloudflare

    env:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.TF_VAR_cloudflare_zone_id }}
      TF_VAR_home_assistant_api_key: ${{ secrets.TF_VAR_home_assistant_api_key }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.tf_token }}
          terraform_version: 1.1.2

      - name: terraform fmt
        run: terraform fmt -recursive

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -auto-approve
