name: provision
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ww3/**
      - anurag-sh/**
      - weather/**
      - cloudflare/**
      - azure/**
      - aws/**
      - tf-state/**
      - maccas/**
      - places/**
      - replybot/**
      - redis-cluster/**
      - sandbox/**
      - graph/**
      - openai/**
      - upstash/**
      - module/**
      - pta/**
      - ozb/**
      - wireguard/**
      - .github/workflows/call-terraform.yml
      - .github/workflows/provision.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tf-state:
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: tf-state
      use-backend-config: false
    secrets: inherit

  upstash:
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: upstash
    secrets: inherit
    needs: tf-state

  redis:
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: redis
      use-fly: true
    secrets: inherit
    needs: tf-state

  cloud:
    name: ${{ matrix.directory }}
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    needs:
      - tf-state
      - upstash
      - redis

    strategy:
      fail-fast: false
      matrix:
        directory:
          - azure
          - aws
          - cloudflare

  shared:
    name: ${{ matrix.directory }}
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    needs: cloud

    strategy:
      fail-fast: false
      matrix:
        directory:
          - places
          - graph
          - openai

  projects:
    name: ${{ matrix.directory }}
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    needs:
      - shared

    strategy:
      fail-fast: false
      matrix:
        directory:
          - anurag-sh
          - ww3
          - weather
          - sandbox
          - maccas
          - replybot
          - ozb
          - wireguard
          - pta
