name: provision
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - anurag-sh/**
      - azure/**
      - aws/**
      - tf-state/**
      - maccas/**
      - replybot/**
      - redis/**
      - sandbox/**
      - module/**
      - perthtransport/**
      - ozb/**
      - wireguard/**
      - .github/workflows/call-terraform.yml
      - .github/workflows/provision.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tf-state:
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: tf-state
      use-backend-config: false
    secrets: inherit

  cloud:
    name: ${{ matrix.directory }}
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    needs:
      - tf-state

    strategy:
      fail-fast: false
      matrix:
        directory:
          - azure
          - aws

  shared:
    name: ${{ matrix.directory }}
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    needs: cloud

    strategy:
      fail-fast: false
      matrix:
        directory:
          - redis

  projects:
    name: ${{ matrix.directory }}
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    needs:
      - shared

    strategy:
      fail-fast: false
      matrix:
        directory:
          - anurag-sh
          - sandbox
          - maccas
          - replybot
          - ozb
          - wireguard
          - perthtransport
