name: provision
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ww3-api/**
      - weather-api/**
      - cloudflare/**
      - paste-api/**
      - lamp-api/**
      - apim/**
      - .github/workflows/tf.yml
      - .github/workflows/provision.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  ww3-api:
    needs: apim
    uses: ./.github/workflows/tf.yml
    with:
      directory: ww3-api
    secrets:
      tf_token: ${{ secrets.tf_token }}

  weather-api:
    needs: apim
    uses: ./.github/workflows/tf.yml
    with:
      directory: weather-api
    secrets:
      tf_token: ${{ secrets.tf_token }}

  cloudflare:
    uses: ./.github/workflows/tf.yml
    with:
      directory: cloudflare
    secrets:
      tf_token: ${{ secrets.tf_token }}

  lamp-api:
    needs: apim
    uses: ./.github/workflows/tf.yml
    with:
      directory: lamp-api
    secrets:
      tf_token: ${{ secrets.tf_token }}

  apim:
    uses: ./.github/workflows/tf.yml
    with:
      directory: apim
    secrets:
      tf_token: ${{ secrets.tf_token }}
