name: provision
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ww3-api/**
      - anurag-sh/**
      - weather-api/**
      - cloudflare/**
      - light-api/**
      - azure/**
      - aws/**
      - tfc/**
      - maccas-api/**
      - places-api/**
      - kvp-api/**
      - log-api/**
      - sandbox/**
      - module/**
      - .github/workflows/call-terraform.yml
      - .github/workflows/provision.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tfc:
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: tfc
    secrets: inherit

  azure:
    needs: tfc
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: azure
    secrets: inherit

  aws:
    needs: tfc
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: aws
    secrets: inherit

  cloudflare:
    needs: tfc
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: cloudflare
    secrets: inherit

  projects:
    name: ${{ matrix.directory }}
    uses: ./.github/workflows/call-terraform.yml
    with:
      directory: ${{ matrix.directory }}
    secrets: inherit
    needs:
      - azure
      - aws
      - cloudflare

    strategy:
      fail-fast: false
      matrix:
        directory:
          - anurag-sh
          - ww3-api
          - weather-api
          - dota2-api
          - light-api
          - sandbox
          - maccas-api
          - places-api
          - kvp-api
          - log-api
