name: rpi
on:
  push:
    branches: [ main ]
    paths:
      - servers/rpi/**
      - .github/workflows/**

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  HOSTNAME: rpi.anurag.sh
  USERNAME: alarm

jobs:
  update-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./cloud"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: install/update dependencies
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          script: |
            sudo pacman -Syu --noconfirm
            sudo pacman -S --noconfirm archlinux-keyring
            sudo pacman -S --noconfirm --needed docker docker-compose rsync wget
            sudo systemctl enable --now docker

  deploy:
    runs-on: ubuntu-latest
    needs: update-install
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: deploy
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -avz --progress
          remote_path: /home/${{ env.USERNAME }}
          remote_host: ${{ env.HOSTNAME }}
          remote_user: ${{ env.USERNAME }}
          remote_key: ${{ secrets.INSTANCE_KEY }}
          path: servers/rpi

      - name: activate deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.INSTANCE_KEY }}
          script: |
            cd /home/${{ env.USERNAME }}/rpi
            docker-compose up --build -d --remove-orphans
            docker ps
