name: terraform
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      tf_token:
        required: true

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  _:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./${{ inputs.name }}"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.tf_token }}
          terraform_version: 1.1.2

      - name: terraform fmt
        run: terraform fmt -recursive

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -auto-approve
