name: terraform
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
    secrets:
      tf_token:
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./${{ inputs.directory }}"

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.TF_VAR_cloudflare_zone_id }}
      TF_VAR_home_assistant_api_key: ${{ secrets.TF_VAR_home_assistant_api_key }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.tf_token }}
          terraform_version: 1.1.2

      - name: terraform fmt
        run: terraform fmt -recursive

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -auto-approve
