name: weather-api
on:
  push:
    branches: [ main ]
    paths:
      - terraform/weather-api/**
      - .github/workflows/weather-api.yml

jobs:
  uses: ./.github/workflows/terraform.yml
  with:
    name: weather-api
