name: weather-api
on:
  push:
    branches: [ main ]
    paths:
      - terraform/weather-api/**
      - .github/workflows/weather-api.yml

jobs:
  provision:
    uses: ./.github/workflows/terraform.yml
    with:
      name: weather-api
